name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'

 

      - #name: Build application
        #run: npm run build  # Adjust this command based on your build script

      # Restart process managed by PM2
      - name: Restart PM2 process
      - run:  npm run build --if-present
      - run:  pm2 restart backend  # Adjust this command based on your PM2 process name
      

